name: news_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.5
  go_router: ^12.1.0
  google_nav_bar: ^5.0.6
  retrofit: ^4.0.3
  logger: ^2.0.2+1
  json_annotation: ^4.8.1
  dio: ^5.3.3
  flutter_loggy_dio: ^3.0.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  loggy: ^2.0.3
  freezed_annotation: ^2.4.1
  pretty_dio_logger: ^1.3.1
  shimmer: ^3.0.0
  riverpod_annotation: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: ^8.0.3
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  riverpod_lint: ^2.3.3
  riverpod_generator: ^2.3.5
  custom_lint: ^0.5.6

flutter:
  uses-material-design: true
